name: Automasi MLOps (Training Model)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository GitHub kamu
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Siapkan Python versi 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Library yang dibutuhkan (pandas, sklearn, mlflow)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn mlflow

    # 4. Jalankan Training Model
    # PENTING: Kita masuk dulu ke folder MLProject (cd MLProject) baru jalankan python
    - name: Run Model Training
      run: |
        cd MLProject
        python modelling.py

    # 5. Upload Hasil Model (Artifacts)
    # Ini pengganti Docker Hub agar dapat nilai SKILLED
    - name: Upload MLflow Artifacts
      if: always()  # Tetap jalan meskipun ada error kecil
      uses: actions/upload-artifact@v4
      with:
        name: model-hasil-training
        path: MLProject/mlruns/